// chronos-c-backend.rs
// Lowers the Chronos AST directly to C99 code.
// Generated C is compiled by cl.exe (MSVC) or gcc/clang.

use std::fmt::Write as FmtWrite;

/// C code generator: walks the AST and emits C source.
pub struct CBackend {
    output: String,
    indent: usize,
}

impl CBackend {
    pub fn new() -> Self {
        Self { output: String::new(), indent: 0 }
    }

    pub fn generate_program(&mut self, prog: &Program) -> String {
        self.output.clear();
        self.emit_prelude();
        // Type declarations first (structs)
        for item in &prog.items {
            self.emit_type_decl(item);
        }
        // Forward-declare all functions
        for item in &prog.items {
            self.emit_forward_decl(item);
        }
        // Function bodies
        for item in &prog.items {
            self.emit_item(item);
        }
        self.output.clone()
    }

    fn emit_prelude(&mut self) {
        self.output.push_str(r#"/* Generated by Chronos compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>

/* Chronos runtime built-ins */
static void __chr_println_str(const char* s)  { printf("%s\n",  s ? s : ""); }
static void __chr_print_str(const char* s)    { printf("%s",    s ? s : ""); }
static void __chr_println_i64(int64_t v)      { printf("%lld\n",(long long)v); }
static void __chr_print_i64(int64_t v)        { printf("%lld",  (long long)v); }
static void __chr_println_f64(double v)       { printf("%g\n",  v); }
static void __chr_print_f64(double v)         { printf("%g",    v); }
static void __chr_println_bool(bool v)        { printf("%s\n",  v ? "true" : "false"); }
static void __chr_print_bool(bool v)          { printf("%s",    v ? "true" : "false"); }
static void __chr_assert(bool cond, const char* msg) {
    if (!cond) { fprintf(stderr, "assertion failed: %s\n", msg ? msg : ""); exit(1); }
}

/* Generic println/print — dispatches on C type (C11 _Generic).
   Only includes unambiguous types; int64_t is the default for integers. */
#define __chr_println(x) _Generic((x), \
    const char*: __chr_println_str, \
    char*:       __chr_println_str, \
    double:      __chr_println_f64, \
    bool:        __chr_println_bool, \
    default:     __chr_println_i64 \
)(x)
#define __chr_print(x) _Generic((x), \
    const char*: __chr_print_str, \
    char*:       __chr_print_str, \
    double:      __chr_print_f64, \
    bool:        __chr_print_bool, \
    default:     __chr_print_i64 \
)(x)

"#);
    }

    fn c_type(&self, ty: &ChronosType) -> String {
        match ty {
            ChronosType::Void | ChronosType::Never => "void".to_string(),
            ChronosType::Bool => "bool".to_string(),
            ChronosType::Char => "char".to_string(),
            ChronosType::Str  => "const char*".to_string(),
            ChronosType::Int8   => "int8_t".to_string(),
            ChronosType::Int16  => "int16_t".to_string(),
            ChronosType::Int32  => "int32_t".to_string(),
            ChronosType::Int64  => "int64_t".to_string(),
            ChronosType::UInt8  => "uint8_t".to_string(),
            ChronosType::UInt16 => "uint16_t".to_string(),
            ChronosType::UInt32 => "uint32_t".to_string(),
            ChronosType::UInt64 => "uint64_t".to_string(),
            ChronosType::Float32 => "float".to_string(),
            ChronosType::Float64 => "double".to_string(),
            ChronosType::Named { name, .. } => name.clone(),
            ChronosType::Owned(inner)
            | ChronosType::Linear(inner)
            | ChronosType::Affine(inner) => self.c_type(inner),
            ChronosType::Optional(inner) => format!("{}*", self.c_type(inner)),
            _ => "void*".to_string(),
        }
    }

    fn indent_str(&self) -> String { "    ".repeat(self.indent) }

    fn emit_type_decl(&mut self, item: &Item) {
        if let Item::StructDecl(s) = item {
            let _ = write!(self.output, "typedef struct {{\n");
            for f in &s.fields {
                let ty = self.c_type(&f.ty);
                let _ = write!(self.output, "    {} {};\n", ty, f.name);
            }
            let _ = write!(self.output, "}} {};\n\n", s.name);
        }
    }

    fn emit_forward_decl(&mut self, item: &Item) {
        if let Item::FunctionDecl(f) = item {
            let params = self.format_params(&f.signature.params);
            let ret = self.c_type(&f.signature.return_type);
            let _ = write!(self.output, "{} {}({});\n", ret, f.signature.name, params);
        }
    }

    fn format_params(&self, params: &[Parameter]) -> String {
        if params.is_empty() { return "void".to_string(); }
        params.iter()
            .map(|p| format!("{} {}", self.c_type(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn emit_item(&mut self, item: &Item) {
        if let Item::FunctionDecl(f) = item {
            self.emit_function(f);
        }
    }

    fn emit_function(&mut self, f: &FunctionDecl) {
        let params = self.format_params(&f.signature.params);
        let ret = self.c_type(&f.signature.return_type);
        let _ = write!(self.output, "\n{} {}({}) {{\n", ret, f.signature.name, params);
        self.indent += 1;
        for stmt in &f.body {
            self.emit_statement(stmt);
        }
        self.indent -= 1;
        self.output.push_str("}\n");
    }

    fn emit_statement(&mut self, stmt: &Statement) {
        let ind = self.indent_str();
        match stmt {
            Statement::Let { name, ty, value, mutable } => {
                let c_ty = ty.as_ref()
                    .map(|t| self.c_type(t))
                    .unwrap_or_else(|| "void*".to_string());
                // In C99 use const qualifier for immutable bindings,
                // but not when the type already contains "const" or is void*.
                let qualifier = if *mutable || c_ty == "void*" || c_ty.contains("const") {
                    ""
                } else {
                    "const "
                };
                let val = self.emit_expr(value);
                let _ = write!(self.output, "{}{}{} {} = {};\n", ind, qualifier, c_ty, name, val);
            }
            Statement::Return(Some(expr)) => {
                let val = self.emit_expr(expr);
                let _ = write!(self.output, "{}return {};\n", ind, val);
            }
            Statement::Return(None) => {
                let _ = write!(self.output, "{}return;\n", ind);
            }
            Statement::ExprStatement(expr) => {
                // Lift if-expressions and block-expressions to proper C statements.
                match expr {
                    Expression::If { condition, then_branch, else_branch } => {
                        let cond = self.emit_expr(condition);
                        let _ = write!(self.output, "{}if ({}) {{\n", ind, cond);
                        self.indent += 1;
                        self.emit_expr_as_stmts(then_branch);
                        self.indent -= 1;
                        if let Some(else_e) = else_branch {
                            let ind2 = self.indent_str();
                            let _ = write!(self.output, "{}}} else {{\n", ind2);
                            self.indent += 1;
                            self.emit_expr_as_stmts(else_e);
                            self.indent -= 1;
                        }
                        let ind3 = self.indent_str();
                        let _ = write!(self.output, "{}}}\n", ind3);
                    }
                    Expression::Block(stmts) => {
                        for s in stmts { self.emit_statement(s); }
                    }
                    _ => {
                        let val = self.emit_expr(expr);
                        let _ = write!(self.output, "{}{};\n", ind, val);
                    }
                }
            }
            Statement::Assignment { target, value } => {
                let lhs = self.emit_expr(target);
                let rhs = self.emit_expr(value);
                let _ = write!(self.output, "{}{} = {};\n", ind, lhs, rhs);
            }
            Statement::While { condition, body } => {
                let cond = self.emit_expr(condition);
                let _ = write!(self.output, "{}while ({}) {{\n", ind, cond);
                self.indent += 1;
                for s in body { self.emit_statement(s); }
                self.indent -= 1;
                let _ = write!(self.output, "{}}}\n", ind);
            }
            Statement::For { binding, iterator, body } => {
                let iter = self.emit_expr(iterator);
                // Chronos for-in over an integer range is the common case.
                // We emit a comment and a placeholder; proper range handling
                // requires knowing the iterator type.
                let _ = write!(self.output, "{}/* for {} in {} */\n", ind, binding, iter);
                let _ = write!(self.output, "{}{{ /* TODO: expand iterator */ }}\n", ind);
                let _ = body; // suppress unused warning
            }
            Statement::Drop(name) => {
                let _ = write!(self.output, "{}/* drop {} */\n", ind, name);
            }
            Statement::Break => {
                let _ = write!(self.output, "{}break;\n", ind);
            }
            Statement::Continue => {
                let _ = write!(self.output, "{}continue;\n", ind);
            }
            Statement::Require { condition, message } => {
                let cond = self.emit_expr(condition);
                let msg = message.as_ref()
                    .map(|m| self.emit_expr(m))
                    .unwrap_or_else(|| "\"assertion failed\"".to_string());
                let _ = write!(self.output, "{}__chr_assert({}, {});\n", ind, cond, msg);
            }
            Statement::DeviceScope { body, .. } => {
                // CPU fallback: emit the body directly.
                for s in body { self.emit_statement(s); }
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expression) -> String {
        match expr {
            Expression::IntLiteral(n) => format!("{}LL", n),
            Expression::FloatLiteral(f) => format!("{}", f),
            Expression::BoolLiteral(b) => if *b { "true".to_string() } else { "false".to_string() },
            Expression::StringLiteral(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r");
                format!("\"{}\"", escaped)
            }
            Expression::Identifier(name) => name.clone(),
            Expression::BinaryOp { left, op, right } => {
                let l = self.emit_expr(left);
                let r = self.emit_expr(right);
                let c_op = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    BinOp::Eq  => "==",
                    BinOp::Neq => "!=",
                    BinOp::Lt  => "<",
                    BinOp::Gt  => ">",
                    BinOp::Lte => "<=",
                    BinOp::Gte => ">=",
                    BinOp::And => "&&",
                    BinOp::Or  => "||",
                    BinOp::BitAnd => "&",
                    BinOp::BitOr  => "|",
                    BinOp::Xor => "^",
                    BinOp::Shl => "<<",
                    BinOp::Shr => ">>",
                    BinOp::MatMul => {
                        return format!("/* matmul({}, {}) */0", l, r);
                    }
                    BinOp::Assign    => return format!("({} = {})", l, r),
                    BinOp::AddAssign => return format!("({} += {})", l, r),
                    BinOp::SubAssign => return format!("({} -= {})", l, r),
                    BinOp::MulAssign => return format!("({} *= {})", l, r),
                    BinOp::DivAssign => return format!("({} /= {})", l, r),
                    BinOp::ModAssign => return format!("({} %= {})", l, r),
                };
                format!("({} {} {})", l, c_op, r)
            }
            Expression::UnaryOp { op, expr } => {
                let e = self.emit_expr(expr);
                let c_op = match op {
                    UnaryOp::Neg    => "-",
                    UnaryOp::Not    => "!",
                    UnaryOp::BitNot => "~",
                    UnaryOp::Deref  => "*",
                    UnaryOp::Ref | UnaryOp::MutRef => "&",
                };
                format!("({}{})", c_op, e)
            }
            Expression::Call { function, args } => {
                let fname = match function.as_ref() {
                    Expression::Identifier(name) => name.clone(),
                    other => self.emit_expr(other),
                };
                let c_args: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                // Map Chronos built-ins to C runtime helpers.
                match fname.as_str() {
                    "println" | "print_line" => {
                        if args.is_empty() {
                            return "printf(\"\\n\")".to_string();
                        }
                        if args.len() == 1 {
                            // Use typed helper for literals; generic macro for identifiers/exprs.
                            let (helper, arg_c) = self.println_call_for_arg(&args[0], &c_args[0]);
                            return format!("{}({})", helper, arg_c);
                        }
                        // Multi-arg: build a printf call with inferred format string.
                        let mut fmt = String::new();
                        let mut fargs: Vec<String> = Vec::new();
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 { fmt.push(' '); }
                            match arg {
                                Expression::StringLiteral(_) => { fmt.push_str("%s"); fargs.push(c_args[i].clone()); }
                                Expression::FloatLiteral(_) => { fmt.push_str("%g"); fargs.push(c_args[i].clone()); }
                                Expression::BoolLiteral(_) => { fmt.push_str("%s"); fargs.push(format!("({}) ? \"true\" : \"false\"", c_args[i])); }
                                _ => { fmt.push_str("%lld"); fargs.push(format!("(long long)({})", c_args[i])); }
                            }
                        }
                        fmt.push_str("\\n");
                        if fargs.is_empty() {
                            return format!("printf(\"{}\")", fmt);
                        }
                        return format!("printf(\"{}\", {})", fmt, fargs.join(", "));
                    }
                    "print" => {
                        if args.is_empty() {
                            return "/* print() */".to_string();
                        }
                        if args.len() == 1 {
                            let (helper, arg_c) = self.print_call_for_arg(&args[0], &c_args[0]);
                            return format!("{}({})", helper, arg_c);
                        }
                        // Multi-arg print: same as println but no trailing newline.
                        let mut fmt = String::new();
                        let mut fargs: Vec<String> = Vec::new();
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 { fmt.push(' '); }
                            match arg {
                                Expression::StringLiteral(_) => { fmt.push_str("%s"); fargs.push(c_args[i].clone()); }
                                Expression::FloatLiteral(_) => { fmt.push_str("%g"); fargs.push(c_args[i].clone()); }
                                Expression::BoolLiteral(_) => { fmt.push_str("%s"); fargs.push(format!("({}) ? \"true\" : \"false\"", c_args[i])); }
                                _ => { fmt.push_str("%lld"); fargs.push(format!("(long long)({})", c_args[i])); }
                            }
                        }
                        if fargs.is_empty() {
                            return format!("printf(\"{}\")", fmt);
                        }
                        return format!("printf(\"{}\", {})", fmt, fargs.join(", "));
                    }
                    "assert" => {
                        if c_args.len() >= 2 {
                            format!("__chr_assert({}, {})", c_args[0], c_args[1])
                        } else {
                            format!(
                                "__chr_assert({}, \"assertion failed\")",
                                c_args.first().map(|s| s.as_str()).unwrap_or("false")
                            )
                        }
                    }
                    "exit" | "abort" => {
                        format!(
                            "exit({})",
                            c_args.first().map(|s| s.as_str()).unwrap_or("0")
                        )
                    }
                    _ => format!("{}({})", fname, c_args.join(", ")),
                }
            }
            Expression::MethodCall { object, method, args } => {
                let obj = self.emit_expr(object);
                let c_args: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                match method.as_str() {
                    "to_string" => format!("/* {}.to_string() */NULL", obj),
                    "len"       => format!("strlen({})", obj),
                    _ => {
                        if c_args.is_empty() {
                            format!("{}_{}({})", obj, method, obj)
                        } else {
                            format!("{}_{}({}, {})", obj, method, obj, c_args.join(", "))
                        }
                    }
                }
            }
            Expression::FieldAccess { object, field } => {
                let obj = self.emit_expr(object);
                format!("{}.{}", obj, field)
            }
            Expression::If { condition, then_branch, else_branch } => {
                let cond = self.emit_expr(condition);
                let then_e = self.emit_expr(then_branch);
                match else_branch {
                    Some(els) => {
                        let else_e = self.emit_expr(els);
                        format!("({} ? {} : {})", cond, then_e, else_e)
                    }
                    None => format!("({} ? {} : (void)0)", cond, then_e),
                }
            }
            Expression::Block(stmts) => {
                if stmts.is_empty() { return "0".to_string(); }
                // Single-statement shortcut.
                if stmts.len() == 1 {
                    match &stmts[0] {
                        Statement::ExprStatement(e) => return self.emit_expr(e),
                        Statement::Return(Some(e))  => return self.emit_expr(e),
                        _ => {}
                    }
                }
                // Multi-statement: use GCC/Clang statement expression extension.
                let mut s = String::from("({ ");
                for stmt in stmts {
                    match stmt {
                        Statement::ExprStatement(e) => {
                            let v = self.emit_expr(e);
                            let _ = write!(s, "{}; ", v);
                        }
                        Statement::Return(Some(e)) => {
                            let v = self.emit_expr(e);
                            let _ = write!(s, "{}; ", v);
                        }
                        _ => { s.push_str("0; "); }
                    }
                }
                s.push_str("})");
                s
            }
            Expression::Return(e) => {
                let val = self.emit_expr(e);
                format!("return {}", val)
            }
            Expression::Await(e) => self.emit_expr(e), // sync fallback
            Expression::TypeAscription { expr, .. } => self.emit_expr(expr),
            Expression::Lambda { params, body, .. } => {
                let _ = params;
                let _ = self.emit_expr(body);
                "/* lambda */NULL".to_string()
            }
            Expression::AiInvoke { skill_name, .. } => {
                format!("/* ai_invoke({}) */NULL", skill_name)
            }
            Expression::TensorLiteral { .. } => "/* tensor */NULL".to_string(),
            Expression::Match { .. }          => "/* match */0".to_string(),
        }
    }

    /// Emit an expression as one or more C statements (used for if/else branches).
    fn emit_expr_as_stmts(&mut self, expr: &Expression) {
        match expr {
            Expression::Block(stmts) => {
                for s in stmts { self.emit_statement(s); }
            }
            Expression::If { condition, then_branch, else_branch } => {
                // Nested if — recurse via emit_statement.
                self.emit_statement(&Statement::ExprStatement(Expression::If {
                    condition: condition.clone(),
                    then_branch: then_branch.clone(),
                    else_branch: else_branch.clone(),
                }));
            }
            _ => {
                let ind = self.indent_str();
                let val = self.emit_expr(expr);
                let _ = write!(self.output, "{}{};\n", ind, val);
            }
        }
    }

    /// Return (helper_fn, c_arg) for a single-arg println call.
    fn println_call_for_arg<'a>(&self, arg: &Expression, c_arg: &'a str) -> (&'static str, String) {
        match arg {
            Expression::StringLiteral(_) => ("__chr_println_str", c_arg.to_string()),
            Expression::FloatLiteral(_)  => ("__chr_println_f64", c_arg.to_string()),
            Expression::BoolLiteral(_)   => ("__chr_println_bool", c_arg.to_string()),
            Expression::IntLiteral(_)    => ("__chr_println_i64", format!("(int64_t)({})", c_arg)),
            // For identifiers/expressions, use the _Generic macro for runtime dispatch.
            _                            => ("__chr_println", c_arg.to_string()),
        }
    }

    /// Return (helper_fn, c_arg) for a single-arg print (no newline) call.
    fn print_call_for_arg<'a>(&self, arg: &Expression, c_arg: &'a str) -> (&'static str, String) {
        match arg {
            Expression::StringLiteral(_) => ("__chr_print_str", c_arg.to_string()),
            Expression::FloatLiteral(_)  => ("__chr_print_f64", c_arg.to_string()),
            Expression::BoolLiteral(_)   => ("__chr_print_bool", c_arg.to_string()),
            Expression::IntLiteral(_)    => ("__chr_print_i64", format!("(int64_t)({})", c_arg)),
            _                            => ("__chr_print", c_arg.to_string()),
        }
    }
}
